sudo: required
services:
  - docker

before_install:
  - docker build -t nelobaba/docker-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true nelobaba/docker-test npm run test
after_success:
  - docker build -t nelobaba/multi-client ./client #build each project docker images for docker hub
  - docker build -t nelobaba/multi-nginx ./nginx
  - docker build -t nelobaba/multi-server ./server
  - docker build -t nelobaba/multi-worker ./worker

  #push images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nelobaba/multi-client
  - docker push nelobaba/multi-nginx 
  - docker push nelobaba/multi-server 
  - docker push nelobaba/multi-worker 
# deploy:
#   provider: elasticbeanstalk
#   region: "ca-central-1"
#   app: "dockerize"
#   env: "Dockerize-env"
#   bucket_name: "elasticbeanstalk-ca-central-1-645095867705"
#   bucket_path: "dockerize"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_ACCESS_SECRET